### ISSUE TITLE
the difference "/" in python2 ande python3

### ISSUE THREAD

**Issue by ShiYaya** [entalent/coco-caption-py3#1]
did you test "/" in python2 and python3 because they are difference .
i want to know whether "/" has influence

**Comment by entalent** [comment]
I tested the original python 2 version and this python 3 version, all the calculated scores are identical, so I didn't pay much attention on the division operation. I will check the types of variables involved in all division operations later.

**Comment by entalent** [comment]
Here are all division operations in the python code:
rouge.py
line 65: `prec.append(lcs/float(len(token_c)))`
line 66: `rec.append(lcs/float(len(token_r)))`
line 72: `score = ((1 + self.beta**2)*prec_max*rec_max)/float(rec_max + self.beta**2*prec_max)`

coco.py     
Note that these lines of code could not be reached when evaluating captions
line 242: `poly = np.array(seg).reshape((len(seg)/2, 2))`
line 250: `color_mask = np.array([2.0,166.0,101.0])/255`

bleu_scorer.py
line 52: `reflen = float(sum(reflen))/len(reflen)`
line 187: `reflen = float(sum(reflens))/len(reflens)`
line 234 - 235: `bleu *= (float(comps['correct'][k]) + tiny) \`
                        `/(float(comps['guess'][k]) + small) `
line 236: `bleu_list[k].append(bleu ** (1./(k+1)))`
line 237: `ratio = (testlen + tiny) / (reflen + small)       # tiny and small defined in line 201 and 202`
line 240: `bleu_list[k][-1] *= math.exp(1 - 1/ratio)`
line 251 - 252: `bleu *= float(totalcomps['correct'][k] + tiny) \`
                    `/ (totalcomps['guess'][k] + small)`
line 253: `bleus.append(bleu ** (1./(k+1)))`
line 254: `ratio = (self._testlen + tiny) / (self._reflen + small)`
line 257: `bleus[k] *= math.exp(1 - 1/ratio)`

cider_scorer.py
line 154: `val[n] /= (norm_hyp[n]*norm_ref[n])       # val is float array, defined in line 146`
line 158: `val[n] *= np.e**(-(delta**2)/(2*self.sigma**2))   # delta is float, defined in line 144`
line 176: `score_avg /= len(refs)        # score_avg is float`

These lines are identical to corresponding lines in https://github.com/tylin/coco-caption, and all division operations involve at least one float variable.
